general:
  ENV_NAME: "BreakoutNoFrameskip-v4"
  TOTAL_TRAINING_STEPS: 1000000
  LOG_INTERVAL: 1000
  SAVE_INTERVAL: 50000
  VIDEO_SAVE_INTERVAL: 10000
  MODEL_SAVE_DIR: "./saved_models"
  RANDOM_SEED: 42
  EVAL_EPISODES: 100
  EVAL_EPSILON: 0.01
  VICTORY_THRESHOLD: 10.0

dqn:
  REPLAY_BUFFER_CAPACITY: 200000
  LEARNING_RATE: 0.0001
  GAMMA: 0.99
  BATCH_SIZE: 64
  TARGET_UPDATE_FREQUENCY: 5000
  EPSILON_START: 1.0
  EPSILON_END: 0.01
  EPSILON_DECAY_STEPS: 1000000
  LEARNING_STARTS: 10000
  GRAD_CLIP_VALUE: 5.0
  USE_PRIORITIZED_REPLAY: false
  PER_ALPHA: 0.6
  PER_BETA_START: 0.4
  PER_BETA_INCREMENT: 0.001
  PER_EPSILON: 0.01

random: {}
